'use strict';
// Every row is complete: Traditional Chinese, English, Simplified Chinese,
// Japanese, German, French, Russian. Original poems are never translated here.
const localeNames=['zh-Hant','en','zh-Hans','ja','de','fr','ru'];
const localeRows=[
['點陣體 · 預設，已包含','Pixel typeface · default, included','点阵体 · 默认，已包含','ドット書体 · 標準、追加料金なし','Pixelschrift · Standard, inklusive','Police matricielle · par défaut, incluse','Пиксельный шрифт · по умолчанию, включён'],
['網站字體 · +£1.99','Website typefaces · +£1.99','网站字体 · +£1.99','サイトの書体 · +£1.99','Website-Schriften · +1,99 £','Polices du site · +1,99 £','Шрифты сайта · +1,99 £'],
['網站字體版本','Website typeface edition','网站字体版本','サイト書体版','Website-Schriftenausgabe','Édition avec les polices du site','Версия со шрифтами сайта'],
['各語言的點陣字體均預設包含，使用 24／36 點整倍字形。網站字體 +£1.99，包含 EB Garamond 與網站的中日文字體，提供 22／24／26 點。附加英譯 +£1.99，僅提供已有原站英譯的作品。','Pixel typefaces are included by default for every supported language, at exact 24/36-dot sizes. Website typefaces add £1.99: EB Garamond and the site’s Chinese/Japanese fonts, at 22/24/26 dots. English translation adds £1.99, only for works with an existing published translation.','各语言的点阵字体均默认包含，使用 24／36 点整倍字形。网站字体 +£1.99，包含 EB Garamond 与网站的中日文字体，提供 22／24／26 点。附加英译 +£1.99，仅提供已有原站英译的作品。','各対応言語のドット書体は標準で追加料金なし、24／36ドットの整数倍で描画します。サイトの書体は +£1.99。EB Garamond とサイトの中国語・日本語書体を22／24／26ドットで使用します。英訳は +£1.99、公開済みの英訳がある作品のみ。','Pixelschriften sind für alle unterstützten Sprachen standardmäßig enthalten, mit exakten Rastergrößen von 24/36 Punkten. Website-Schriften kosten 1,99 £ extra: EB Garamond und die chinesischen/japanischen Schriften der Website, in 22/24/26 Punkten. Englische Übersetzung: +1,99 £, nur bei bereits veröffentlichten Übersetzungen.','Les polices matricielles sont incluses par défaut pour toutes les langues prises en charge, en 24/36 points de trame exacts. Les polices du site ajoutent 1,99 £ : EB Garamond et les polices chinoises/japonaises du site, en 22/24/26 points. Traduction anglaise : +1,99 £, uniquement si une traduction a déjà été publiée.','Пиксельные шрифты включены по умолчанию для всех поддерживаемых языков: точные размеры 24/36 точек растра. Шрифты сайта стоят дополнительно 1,99 £: EB Garamond и китайские/японские шрифты сайта, размеры 22/24/26 точек. Английский перевод: +1,99 £, только при наличии опубликованного перевода.'],
['作品介紹','Project overview','作品介绍','作品について','Projektübersicht','Présentation','О проекте'],
['製作室','Studio','制作室','制作室','Gestaltungsraum','Atelier','Мастерская'],
['POETRY VOUCHER / STUDIO','POETRY VOUCHER / STUDIO','诗券 / 制作室','詩の券 / 制作室','POETRY VOUCHER / GESTALTUNG','POETRY VOUCHER / ATELIER','POETRY VOUCHER / МАСТЕРСКАЯ'],
['製作一張詩券','Make a poetry voucher','制作一张诗券','詩の券を作る','Einen Gedichtbon gestalten','Créer un bon poétique','Создать поэтический талон'],
['選詩、排版，帶走一份數位作品。','Choose a poem. Set the type. Take it with you.','选诗、排版，带走一份数字作品。','詩を選び、組んで、持ち帰る。','Gedicht wählen, gestalten, mitnehmen.','Choisir un poème, le composer, l’emporter.','Выберите стихотворение, оформите и сохраните.'],
['內容','Content','内容','内容','Inhalt','Texte','Текст'],
['排版','Typography','排版','組版','Typografie','Typographie','Типографика'],
['校樣','Proof','校样','校正','Vorschau','Épreuve','Проба'],
['帶走作品','Take it with you','带走作品','作品を持ち帰る','Werk mitnehmen','Emporter l’œuvre','Сохранить работу'],
['小票明細與虛構計價','Receipt details & fictional pricing','小票明细与虚构计价','レシート明細と架空の価格','Belegdetails und fiktive Preise','Détail du ticket et prix fictifs','Детали чека и вымышленные цены'],
['現金 · 硬幣支付','Cash · coins','现金 · 硬币支付','現金 · 硬貨払い','Bargeld · Münzen','Espèces · pièces','Наличные · монеты'],
['現金 · 紙幣硬幣混合支付','Cash · notes and coins','现金 · 纸币硬币混合支付','現金 · 紙幣と硬貨','Bargeld · Banknoten und Münzen','Espèces · billets et pièces','Наличные · банкноты и монеты'],
['生成時自動抽取付款場景。','A payment scene is drawn automatically when you generate.','生成时自动抽取付款场景。','生成時に支払い場面を自動抽選します。','Beim Erstellen wird automatisch eine Zahlungsszene ausgelost.','Un scénario de paiement est tiré au sort à la génération.','При создании автоматически выбирается сценарий оплаты.'],
['每次生成隨機安排刷卡、紙幣、硬幣或混合現金；超過 £10 不安排純硬幣。現金足額，找零使用流通面額。切換語言不重抽；全部為虛構交易。','Each generation randomly assigns card, notes, coins or mixed cash; no coins-only scenes above £10. Cash always covers the total, with change in circulating denominations. Language changes do not redraw. All transactions are fictional.','每次生成随机安排刷卡、纸币、硬币或混合现金；超过 £10 不安排纯硬币。现金足额，找零使用流通面额。切换语言不重抽；全部为虚构交易。','生成ごとにカード・紙幣・硬貨・混合現金を抽選します。£10超は硬貨のみを選びません。現金は足額で、お釣りは流通金種を使います。言語変更では再抽選しません。すべて架空取引です。','Jede Erstellung lost Karte, Banknoten, Münzen oder gemischtes Bargeld aus. Über 10 £ keine reine Münzzahlung. Bargeld reicht immer; Wechselgeld nutzt umlaufende Stückelungen. Sprachwechsel lost nicht neu aus. Alle Zahlungen sind fiktiv.','Chaque génération tire au sort carte, billets, pièces ou espèces mixtes. Pas de pièces seules au-delà de 10 £. Les espèces couvrent le total, avec monnaie courante. Changer de langue ne relance pas le tirage. Transactions fictives.','При каждом создании выбираются карта, банкноты, монеты или смешанные наличные. Свыше £10 только монеты не выбираются. Наличных всегда достаточно, сдача — обращающимися номиналами. Смена языка не меняет выбор. Все сделки вымышлены.'],
['虛構交易小票，並非購物憑證','Fictional transaction receipt, not proof of purchase','虚构交易小票，并非购物凭证','架空取引のレシート、購入証明ではありません','Fiktiver Beleg, kein Kaufnachweis','Reçu fictif, sans valeur de preuve d’achat','Вымышленный чек, не подтверждение покупки'],
['付款方式','Payment method','付款方式','支払い方法','Zahlungsart','Mode de paiement','Способ оплаты'],
['現金 · 自動紙幣','Cash · automatic banknotes','现金 · 自动纸币','現金 · 紙幣自動選択','Bargeld · automatische Banknoten','Espèces · billets automatiques','Наличные · автоматический выбор банкнот'],
['現金 · 硬幣付清','Cash · exact coins','现金 · 硬币付清','現金 · 硬貨でちょうど','Bargeld · passend in Münzen','Espèces · appoint en pièces','Наличные · монеты без сдачи'],
['現金 · 紙幣硬幣混合付清','Cash · exact notes and coins','现金 · 纸币硬币混合付清','現金 · 紙幣と硬貨でちょうど','Bargeld · passend gemischt','Espèces · appoint mixte','Наличные · банкноты и монеты без сдачи'],
['現金 · 自選面額與數量','Cash · choose denominations and quantities','现金 · 自选面额与数量','現金 · 金種と枚数を選択','Bargeld · Stückelung und Anzahl wählen','Espèces · choisir valeurs et quantités','Наличные · выбрать номиналы и количество'],
['刷卡 · 模擬交易','Card · simulated transaction','刷卡 · 模拟交易','カード · 模擬取引','Karte · simulierte Zahlung','Carte · transaction simulée','Карта · имитация оплаты'],
['支付現金','Cash tendered','支付现金','支払い現金','Gezahltes Bargeld','Espèces remises','Внесённые наличные'],
['尚欠','Still due','尚欠','不足額','Noch offen','Reste à payer','Не хватает'],
['面額數量須為 0–100 的整數。','Quantities must be whole numbers from 0 to 100.','面额数量须为 0–100 的整数。','枚数は0〜100の整数にしてください。','Anzahlen müssen ganze Zahlen von 0 bis 100 sein.','Les quantités doivent être des entiers de 0 à 100.','Количество должно быть целым числом от 0 до 100.'],
['現金不足，請增加面額數量或更換付款方式。','Insufficient cash. Add notes or coins, or change payment method.','现金不足，请增加面额数量或更换付款方式。','現金が不足しています。枚数を増やすか支払い方法を変更してください。','Zu wenig Bargeld. Stückzahl erhöhen oder Zahlungsart wechseln.','Espèces insuffisantes. Ajoutez des billets ou pièces, ou changez de mode de paiement.','Недостаточно наличных. Добавьте банкноты или монеты либо измените способ оплаты.'],
['模擬刷卡，按總額支付；不收集卡號，不發起付款。','Simulated card payment for the exact total. No card details collected and no payment initiated.','模拟刷卡，按总额支付；不收集卡号，不发起付款。','合計額の模擬カード払いです。カード情報の収集や決済は行いません。','Simulierte Kartenzahlung des Gesamtbetrags. Keine Kartendaten und keine echte Zahlung.','Paiement par carte simulé du montant exact. Aucune donnée bancaire collectée ni aucun paiement lancé.','Имитация оплаты картой на точную сумму. Данные карты не собираются, платёж не выполняется.'],
['自選現金可混合紙幣和硬幣；數量不足不能生成小票。刷卡不收集真實卡資料。','Mix notes and coins in custom cash mode. Insufficient cash prevents receipt generation. Card mode collects no real card details.','自选现金可混合纸币和硬币；数量不足不能生成小票。刷卡不收集真实卡资料。','現金は紙幣と硬貨を混ぜて指定できます。不足時はレシートを生成できません。カード情報は収集しません。','Banknoten und Münzen lassen sich frei kombinieren. Zu wenig Bargeld verhindert den Beleg. Es werden keine Kartendaten erfasst.','Combinez billets et pièces librement. Un montant insuffisant bloque le reçu. Aucune donnée bancaire n’est collectée.','Можно сочетать банкноты и монеты. При недостаточной сумме чек не создаётся. Данные карты не собираются.'],
['倫敦現金模型支援流通紙幣及硬幣，假設庫存充足。自動紙幣模式優先選最小足額紙幣；硬幣或混合模式自動付清。自選模式按指定面額計算找零。','The London cash model uses circulating notes and coins, assuming sufficient stock. Automatic banknotes chooses the smallest sufficient note; coin and mixed modes pay exactly. Custom mode calculates change from selected denominations.','伦敦现金模型支持流通纸币及硬币，假设库存充足。自动纸币模式优先选最小足额纸币；硬币或混合模式自动付清。自选模式按指定面额计算找零。','ロンドンの流通紙幣・硬貨を使用し、在庫は十分と仮定します。紙幣自動は足りる最小の紙幣を選び、硬貨・混合はちょうど支払います。自選は指定金種からお釣りを計算します。','Das Londoner Modell nutzt umlaufende Banknoten und Münzen bei ausreichendem Bestand. Automatik wählt die kleinste ausreichende Note; Münzen und gemischte Zahlung sind passend. Freie Auswahl berechnet das Wechselgeld aus der Stückelung.','Le modèle londonien utilise billets et pièces courants, avec stock suffisant. Le mode billets choisit le plus petit billet suffisant ; pièces et mélange font l’appoint. Le mode libre calcule la monnaie selon les valeurs choisies.','Лондонская модель использует обращающиеся банкноты и монеты при достаточном запасе. Автовыбор берёт наименьшую достаточную банкноту; монеты и смешанный режим дают точную сумму. Ручной режим рассчитывает сдачу по выбранным номиналам.'],
['自選內容','Custom text','自选内容','カスタム本文','Eigener Text','Texte personnalisé','Собственный текст'],
['支付紙幣','Banknotes tendered','支付纸币','支払い紙幣','Gezahlte Banknoten','Billets remis','Внесённые банкноты'],
['PV3：原文按字數、非空行和分節加權，向上調至最近的 £x.99。標點、空格、題名及署名不計字數。網站字體、英譯及自選內容各加 £1.99；自寫或修改原作即屬自選內容。英譯不重複計字費，各商品相加為總價。','PV3: the poem is weighted by characters, non-empty lines and stanzas, then rounded up to the next £x.99. Punctuation, spaces, title and byline are excluded from character counts. Website typefaces, English translation and custom text each add £1.99. Writing your own or editing an original counts as custom text. Translation has no extra character charge; items sum to the total.','PV3：原文按字数、非空行和分节加权，向上调至最近的 £x.99。标点、空格、题名及署名不计字数。网站字体、英译及自选内容各加 £1.99；自写或修改原作即属自选内容。英译不重复计字费，各商品相加为总价。','PV3：文字数、空白でない行、連で加重計算し、次の £x.99 に切り上げます。句読点、空白、題名、署名は文字数に含めません。サイト書体・英訳・カスタム本文は各 +£1.99。自作や原作の編集はカスタム本文です。英訳の文字料金は重複せず、各商品の和が合計です。','PV3: Zeichen, nicht leere Zeilen und Strophen bestimmen den Preis, aufgerundet auf den nächsten Betrag mit ,99 £. Satzzeichen, Leerzeichen, Titel und Name zählen nicht als Zeichen. Website-Schriften, Übersetzung und eigener Text kosten je 1,99 £ extra. Eigene oder bearbeitete Texte gelten als eigener Text. Keine weitere Zeichengebühr für die Übersetzung; Gesamtpreis ist die Artikelsumme.','PV3 : pondération par caractères, lignes non vides et strophes, arrondie au prix supérieur en ,99 £. Ponctuation, espaces, titre et signature sont exclus du nombre de caractères. Polices du site, traduction et texte personnalisé ajoutent chacun 1,99 £. Écrire ou modifier une œuvre compte comme texte personnalisé. Pas de double facturation des caractères traduits ; le total est la somme des articles.','PV3: цена зависит от числа символов, непустых строк и строф, с округлением вверх до ,99 £. Пунктуация, пробелы, название и подпись не входят в число символов. Шрифты сайта, перевод и собственный текст добавляют по 1,99 £. Новый или изменённый текст считается собственным. Перевод не оплачивается посимвольно повторно; итог — сумма позиций.'],
['倫敦現金模式：使用 £5、£10、£20、£50 紙幣，優先選一張足額紙幣，超過 £50 才組合支付。找零按流通紙幣與硬幣拆分，假設庫存充足。','London cash model: £5, £10, £20 and £50 notes. Prefer the smallest single sufficient note; combine notes above £50. Change uses circulating notes and coins, assuming sufficient till stock.','伦敦现金模式：使用 £5、£10、£20、£50 纸币，优先选一张足额纸币，超过 £50 才组合支付。找零按流通纸币与硬币拆分，假设库存充足。','ロンドン現金モデル：£5・£10・£20・£50 紙幣を使用。足りる最小の紙幣1枚を優先し、£50 超は組み合わせます。お釣りは流通紙幣と硬貨で計算し、在庫は十分と仮定します。','Londoner Bargeldmodell: 5-, 10-, 20- und 50-Pfund-Noten. Bevorzugt wird die kleinste ausreichende einzelne Note; über 50 £ werden Noten kombiniert. Wechselgeld aus umlaufenden Noten und Münzen, bei ausreichendem Kassenbestand.','Modèle londonien : billets de 5, 10, 20 et 50 £. Priorité au plus petit billet suffisant ; au-delà de 50 £, combinaison de billets. Monnaie rendue en billets et pièces courants, avec stock supposé suffisant.','Лондонская модель: банкноты £5, £10, £20 и £50. Выбирается наименьшая достаточная банкнота; свыше £50 — комбинация. Сдача выдаётся обращающимися банкнотами и монетами при достаточном запасе.'],
['詩券字體','Voucher typeface','诗券字体','詩券の書体','Schrift der Lyrikkarte','Police du bon poétique','Шрифт поэтического талона'],
['附加英譯','English translation add-on','附加英译','英訳の追加','Englische Übersetzung','Traduction anglaise','Английский перевод'],
['自動計價','Automatic pricing','自动计价','自動価格計算','Automatische Preisberechnung','Calcul automatique du prix','Автоматический расчёт цены'],
['基本費','Base','基础费','基本料金','Grundpreis','Base','Базовая цена'],
['字元','Characters','字符','文字数','Zeichen','Caractères','Символы'],
['非空行','Non-empty lines','非空行','空白でない行','Nicht leere Zeilen','Lignes non vides','Непустые строки'],
['分節','Stanzas','分节','連','Strophen','Strophes','Строфы'],
['找零','Change','找零','お釣り','Wechselgeld','Monnaie rendue','Сдача'],
['PV1：只計正文與所選英譯的字母、漢字及數字，不計標點、空格、題名及署名。空行分節；現金向上取整至一英鎊。這是虛構計價，不評判詩的品質。','PV1: counts letters, Chinese characters and numbers in the poem and selected translation, excluding punctuation, spaces, title and byline. Blank lines separate stanzas; cash rounds up to the next whole pound. Fictional pricing, not a judgement of poetic quality.','PV1：只计正文与所选英译的字母、汉字及数字，不计标点、空格、题名及署名。空行分节；现金向上取整至一英镑。这是虚构计价，不评判诗的品质。','PV1：本文と選択した英訳の文字・数字を数えます。句読点、空白、題名、署名は除外。空行で連を区切り、現金は1ポンド単位で切り上げます。架空の価格で、詩の質を評価しません。','PV1: zählt Buchstaben, chinesische Schriftzeichen und Ziffern im Gedicht und in der gewählten Übersetzung. Satzzeichen, Leerzeichen, Titel und Name zählen nicht. Leerzeilen trennen Strophen; Bargeld wird auf volle Pfund aufgerundet. Fiktive Preise, kein Urteil über die Qualität.','PV1 : compte les lettres, caractères chinois et chiffres du poème et de la traduction choisie, hors ponctuation, espaces, titre et signature. Les lignes vides séparent les strophes ; les espèces sont arrondies à la livre supérieure. Prix fictif, sans jugement sur la qualité du poème.','PV1: учитывает буквы, иероглифы и цифры стихотворения и выбранного перевода, без пунктуации, пробелов, названия и подписи. Пустые строки разделяют строфы; наличные округляются вверх до целого фунта. Вымышленная цена, не оценка качества стихов.'],
['Language','Language','语言','言語','Sprache','Langue','Язык'],
['跳至作品','Skip to the work','跳至作品','作品へ','Zum Werk','Aller à l’œuvre','Перейти к работе'],
['頁面導航','Navigation','页面导航','ナビゲーション','Navigation','Navigation','Навигация'],
['Make yours','Make yours','制作诗券','自分の詩券を作る','Selbst gestalten','Créer le vôtre','Создать свой'],
['About','About','关于作品','作品について','Über das Projekt','À propos','О проекте'],
['Portfolio','Portfolio','作品集','ポートフォリオ','Portfolio','Portfolio','Портфолио'],
['POETRY / INTERACTION / THERMAL PAPER · 2026','POETRY / INTERACTION / THERMAL PAPER · 2026','诗歌 / 交互 / 热敏纸 · 2026','詩 / インタラクション / 感熱紙 · 2026','LYRIK / INTERAKTION / THERMOPAPIER · 2026','POÉSIE / INTERACTION / PAPIER THERMIQUE · 2026','ПОЭЗИЯ / ИНТЕРАКТИВНОСТЬ / ТЕРМОБУМАГА · 2026'],
['詩券','Poetry slip','诗券','詩の券','Gedichtbon','Bon poétique','Поэтический талон'],
['一張小票。','A receipt.','一张小票。','一枚のレシート。','Ein Kassenbon.','Un ticket de caisse.','Кассовый чек.'],
['另一種值得留下的東西。','Something else worth keeping.','另一种值得留下的东西。','残しておきたい、もう一つのもの。','Und etwas, das man behalten möchte.','Autre chose à conserver.','И нечто, что хочется сохранить.'],
['上半張記錄一筆虛構交易，下半張留下完整的詩。借用日常收據的秩序，讓閱讀發生在一條本來很快會被丟棄的紙上。','A fictional transaction above; a complete poem below. The familiar order of a receipt becomes a place to read, on paper usually thrown away.','上半张记录一笔虚构交易，下半张留下完整的诗。借用日常收据的秩序，让阅读发生在一条本来很快会被丢弃的纸上。','上半分には架空の取引、下半分には一編の詩。日常のレシートの形式を借り、捨てられがちな紙を読む場所に変えます。','Oben eine fiktive Transaktion, unten ein vollständiges Gedicht. Die vertraute Ordnung eines Kassenbons wird zum Leseraum auf Papier, das sonst im Müll landet.','Une transaction fictive en haut, un poème entier en bas. La structure familière du ticket devient un espace de lecture sur un papier habituellement jeté.','Сверху вымышленная покупка, снизу целое стихотворение. Привычная структура чека превращает одноразовую бумагу в место для чтения.'],
['選一首，或寫下自己的','Choose a poem, or write your own','选一首，或写下自己的','詩を選ぶ、または自分で書く','Ein Gedicht wählen oder selbst schreiben','Choisir un poème ou écrire le vôtre','Выберите стихотворение или напишите своё'],
['MADE IN YOUR BROWSER · NO REMOTE PRINTING','MADE IN YOUR BROWSER · NO REMOTE PRINTING','浏览器本地生成 · 不远程打印','ブラウザー内で作成 · 遠隔印刷なし','LOKAL IM BROWSER · KEIN FERNDRUCK','CRÉATION LOCALE · AUCUNE IMPRESSION À DISTANCE','СОЗДАНИЕ В БРАУЗЕРЕ · БЕЗ УДАЛЁННОЙ ПЕЧАТИ'],
['Make an edition','Make an edition','制作版本','一枚を作る','Eine Ausgabe gestalten','Créer une édition','Создать экземпляр'],
['製作詩券','Poetry voucher','制作诗券','詩券を作る','Gedichtbon','Bon poétique','Поэтический талон'],
['58 MM PAPER / 384 DOTS / 1 BIT','58 MM PAPER / 384 DOTS / 1 BIT','58 毫米纸宽 / 384 点 / 1 位','紙幅 58 MM / 384 ドット / 1 ビット','58 MM PAPIER / 384 PUNKTE / 1 BIT','PAPIER 58 MM / 384 POINTS / 1 BIT','БУМАГА 58 ММ / 384 ТОЧКИ / 1 БИТ'],
['作品編輯器','Poem editor','作品编辑器','詩の編集','Gedichteditor','Éditeur de poème','Редактор стихотворения'],
['01 / SELECT & COMPOSE','01 / SELECT & COMPOSE','01 / 选择与创作','01 / 選択と編集','01 / AUSWÄHLEN UND SCHREIBEN','01 / CHOISIR ET ÉCRIRE','01 / ВЫБОР И СОЗДАНИЕ'],
['從作品開始','Start with a work','从作品开始','作品から始める','Mit einem Werk beginnen','Partir d’une œuvre','Выберите произведение'],
['載入作品…','Loading works…','载入作品…','作品を読み込み中…','Werke werden geladen…','Chargement des œuvres…','Загрузка произведений…'],
['版本','Poem version','版本','詩の版','Gedichtfassung','Version du poème','Версия стихотворения'],
['原文','Original text','原文','原文','Originaltext','Texte original','Оригинал'],
['原文與站上英譯','Original + published English translation','原文与原站英译','原文と公開済み英訳','Original + veröffentlichte englische Übersetzung','Original + traduction anglaise publiée','Оригинал + опубликованный английский перевод'],
['字號 / dots','Type size / dots','字号 / 点','文字サイズ / ドット','Schriftgröße / Punkte','Corps / points','Размер шрифта / точки'],
['題名','Title','题名','題名','Titel','Titre','Название'],
['署名','Byline','署名','署名','Verfasserangabe','Signature','Подпись автора'],
['正文 / 保留分行與分節','Poem / keep line and stanza breaks','正文 / 保留分行与分节','本文 / 改行と連を保持','Gedicht / Zeilen und Strophen beibehalten','Poème / conserver les vers et les strophes','Текст / сохраняйте строки и строфы'],
['小票設定','Receipt settings','小票设置','レシート設定','Kassenbon-Einstellungen','Réglages du ticket','Настройки чека'],
['標價 / GBP','Price / GBP','标价 / GBP','価格 / GBP','Preis / GBP','Prix / GBP','Цена / GBP'],
['現金 / GBP','Cash tendered / GBP','现金 / GBP','預かり現金 / GBP','Barzahlung / GBP','Espèces remises / GBP','Внесено наличными / GBP'],
['找零自動計算。僅為藝術樣本，不會收費；不填入真實銀行、會員或硬件身份資料。','Change is calculated automatically. This is an art specimen, not a payment. Do not enter real banking, loyalty or hardware identifiers.','找零自动计算。仅为艺术样本，不会收费；不填入真实银行、会员或硬件身份资料。','お釣りは自動計算されます。作品用の見本で、請求はありません。実際の銀行・会員・機器識別情報は入力しないでください。','Das Wechselgeld wird automatisch berechnet. Dies ist ein Kunstmuster, keine Zahlung. Keine echten Bank-, Kunden- oder Gerätekennungen eingeben.','La monnaie est calculée automatiquement. Il s’agit d’une œuvre, pas d’un paiement. Ne saisissez aucun identifiant bancaire, de fidélité ou d’appareil réel.','Сдача рассчитывается автоматически. Это художественный образец, не оплата. Не вводите реальные банковские, клиентские или аппаратные идентификаторы.'],
['製作我的詩券','Make my poetry voucher','制作我的诗券','詩券を作る','Meinen Gedichtbon erstellen','Créer mon bon poétique','Создать мой талон'],
['正在載入作品…','Loading works…','正在载入作品…','作品を読み込み中…','Werke werden geladen…','Chargement des œuvres…','Загрузка произведений…'],
['文字只在這個瀏覽器頁面中處理，不上傳、不自動儲存。下載不會讓 H10S 出紙；離開前請保存作品。','Text is processed only in this browser page. It is not uploaded or saved automatically. Downloads do not print on the H10S. Save your work before leaving.','文字只在这个浏览器页面中处理，不上传、不自动保存。下载不会让 H10S 出纸；离开前请保存作品。','文字はこのブラウザー内だけで処理され、送信・自動保存されません。ダウンロードしても H10S は印刷しません。ページを離れる前に保存してください。','Der Text bleibt in dieser Browserseite und wird weder hochgeladen noch automatisch gespeichert. Downloads lösen keinen H10S-Druck aus. Vor dem Verlassen bitte speichern.','Le texte reste dans cette page, sans envoi ni sauvegarde automatique. Le téléchargement ne déclenche pas l’imprimante H10S. Enregistrez avant de quitter.','Текст обрабатывается только на этой странице, без отправки и автосохранения. Скачивание не запускает H10S. Сохраните работу перед уходом.'],
['數位校樣','Digital proof','数字校样','デジタル校正','Digitale Druckvorschau','Épreuve numérique','Цифровая проба'],
['02 / DIGITAL PROOF','02 / DIGITAL PROOF','02 / 数字校样','02 / デジタル校正','02 / DIGITALE DRUCKVORSCHAU','02 / ÉPREUVE NUMÉRIQUE','02 / ЦИФРОВАЯ ПРОБА'],
['預覽方式','Preview mode','预览方式','プレビュー表示','Vorschaumodus','Mode d’aperçu','Режим просмотра'],
['分開看','Separate pieces','分开看','別々に見る','Getrennt','Séparément','Раздельно'],
['完整紙條','Full strip','完整纸条','紙全体','Gesamter Streifen','Bande entière','Полная лента'],
['讀原文','Read the text','读原文','本文を読む','Text lesen','Lire le texte','Читать текст'],
['01 — RECEIPT / 小票','01 — RECEIPT','01 — 小票','01 — レシート','01 — KASSENBON','01 — TICKET','01 — ЧЕК'],
['02 — VOUCHER / 詩券','02 — POETRY VOUCHER','02 — 诗券','02 — 詩券','02 — GEDICHTBON','02 — BON POÉTIQUE','02 — ПОЭТИЧЕСКИЙ ТАЛОН'],
['RECEIPT + VOUCHER / 連續紙條','RECEIPT + VOUCHER / FULL STRIP','小票 + 诗券 / 连续纸条','レシート + 詩券 / 紙全体','KASSENBON + GEDICHT / GESAMTER STREIFEN','TICKET + BON / BANDE ENTIÈRE','ЧЕК + ТАЛОН / ПОЛНАЯ ЛЕНТА'],
['虛構現金交易小票，並非購物憑證','Fictional cash receipt, not proof of purchase','虚构现金交易小票，并非购物凭证','架空の現金取引。購入証明ではありません','Fiktiver Kassenbon, kein Kaufbeleg','Ticket fictif, sans valeur de preuve d’achat','Вымышленный чек, не подтверждение покупки'],
['詩券排版；可切換讀原文取得文字版','Poetry voucher; choose Read the text for an accessible version','诗券排版；可切换读原文查看文字版','詩券のレイアウト。本文表示で文字を読めます','Gedichtbon; Textansicht für barrierefreies Lesen','Bon poétique ; choisir la vue texte pour une lecture accessible','Вёрстка талона; текст доступен в режиме чтения'],
['小票、CUT HERE 分隔及完整詩券','Receipt, CUT HERE separator and complete poetry voucher','小票、CUT HERE 分隔及完整诗券','レシート、切り取り線、詩券全体','Kassenbon, Schnittlinie und vollständiger Gedichtbon','Ticket, ligne de découpe et bon poétique complet','Чек, линия отреза и полный поэтический талон'],
['下載數位作品','Download your edition','下载数字作品','作品をダウンロード','Ausgabe herunterladen','Télécharger l’édition','Скачать экземпляр'],
['詩券 PDF','Voucher PDF','诗券 PDF','詩券 PDF','Gedicht-PDF','Bon PDF','Талон PDF'],
['小票 PDF','Receipt PDF','小票 PDF','レシート PDF','Kassenbon-PDF','Ticket PDF','Чек PDF'],
['完整 PDF','Full PDF','完整 PDF','全体 PDF','Gesamt-PDF','PDF complet','Полный PDF'],
['03 / PROJECT NOTES','03 / PROJECT NOTES','03 / 项目说明','03 / プロジェクトノート','03 / PROJEKTNOTIZEN','03 / NOTES DU PROJET','03 / О ПРОЕКТЕ'],
['From till','From till','从收银','レジから','Von der Kasse','De la caisse','От кассы'],
['to text.','to text.','到文字。','詩へ。','zum Text.','au texte.','к тексту.'],
['詩歌 × 排印 × 嵌入式硬件','Poetry × typography × embedded hardware','诗歌 × 排印 × 嵌入式硬件','詩 × タイポグラフィ × 組込み機器','Lyrik × Typografie × eingebettete Hardware','Poésie × typographie × matériel embarqué','Поэзия × типографика × встроенное оборудование'],
['兩種文字的速度','Two speeds of reading','两种文字的速度','二つの読む速度','Zwei Lesegeschwindigkeiten','Deux rythmes de lecture','Два темпа чтения'],
['日常格式，不是憑證','A familiar format, not a receipt of payment','日常格式，不是凭证','日常の形式、購入証明ではなく','Vertrautes Format, kein Zahlungsbeleg','Un format quotidien, pas une preuve de paiement','Привычная форма, не подтверждение оплаты'],
['為一台真實機器而作','Made for a real machine','为一台真实机器而作','実在の機器のために','Für ein echtes Gerät','Pour une véritable machine','Для настоящего устройства'],
['你也可以帶走一張','Take one of your own','你也可以带走一张','あなたの一枚を持ち帰る','Ein eigenes Exemplar mitnehmen','Emportez le vôtre','Заберите свой экземпляр'],
['POETRY VOUCHER · DIGITAL STUDY · 2026','POETRY VOUCHER · DIGITAL STUDY · 2026','诗券 · 数字实验 · 2026','詩券 · デジタル実験 · 2026','POETRY VOUCHER · DIGITALE STUDIE · 2026','POETRY VOUCHER · ÉTUDE NUMÉRIQUE · 2026','POETRY VOUCHER · ЦИФРОВОЙ ЭТЮД · 2026'],
['Back to portfolio','Back to portfolio','返回作品集','ポートフォリオに戻る','Zurück zum Portfolio','Retour au portfolio','Вернуться к портфолио'],
['＋ 寫自己的詩','＋ Write your own','＋ 写自己的诗','＋ 自分の詩を書く','＋ Eigenes Gedicht schreiben','＋ Écrire votre poème','＋ Написать своё'],
['寫下自己的作品。署名留空也可以。','Write your own work. The byline is optional.','写下自己的作品。署名也可留空。','自分の作品を書いてください。署名は空欄でも構いません。','Schreiben Sie Ihr eigenes Werk. Die Verfasserangabe ist optional.','Écrivez votre œuvre. La signature est facultative.','Напишите своё произведение. Подпись необязательна.'],
['內容已改動；點「製作我的詩券」更新校樣。','Edits not yet rendered. Make your voucher to update the proof.','内容已改动；请重新制作以更新校样。','変更は未反映です。詩券を作成して校正を更新してください。','Änderungen noch nicht gesetzt. Erstellen Sie den Bon neu.','Modifications non composées. Créez le bon pour actualiser l’épreuve.','Изменения ещё не свёрстаны. Создайте талон заново.'],
['金額請填 0–999.99，最多兩位小數。','Enter 0–999.99, with at most two decimal places.','金额请填 0–999.99，最多两位小数。','金額は 0–999.99、小数点以下2桁までです。','Betrag: 0–999.99, höchstens zwei Nachkommastellen.','Montant : 0–999.99, deux décimales maximum.','Сумма: 0–999.99, не более двух знаков после точки.'],
['這份文字超過紙條長度上限，請縮短正文或減小字號。','The strip is too long. Shorten the text or reduce the type size.','文字超过纸条长度上限，请缩短正文或减小字号。','紙の長さの上限を超えました。本文を短くするか文字を小さくしてください。','Der Streifen ist zu lang. Text kürzen oder Schrift verkleinern.','La bande est trop longue. Raccourcissez le texte ou réduisez le corps.','Лента слишком длинная. Сократите текст или уменьшите шрифт.'],
['小票欄位過長。','Receipt field too long.','小票字段过长。','レシートの項目が長すぎます。','Kassenbonfeld zu lang.','Champ du ticket trop long.','Слишком длинное поле чека.'],
['不支援的小票字元。','Unsupported receipt character.','不支持的小票字符。','対応していないレシート文字です。','Nicht unterstütztes Zeichen im Bon.','Caractère non pris en charge sur le ticket.','Неподдерживаемый символ чека.'],
['在此裝置排版中…','Typesetting on this device…','正在此设备排版…','この端末で組版中…','Satz auf diesem Gerät…','Composition sur cet appareil…','Вёрстка на этом устройстве…'],
['請填寫題名和正文。','Please enter a title and poem.','请填写题名和正文。','題名と本文を入力してください。','Bitte Titel und Gedicht eingeben.','Saisissez un titre et un poème.','Введите название и текст.'],
['文字超出長度上限。','Text exceeds the length limit.','文字超出长度上限。','文字数の上限を超えています。','Text überschreitet die Längenbegrenzung.','Le texte dépasse la longueur autorisée.','Текст превышает допустимую длину.'],
['文字包含不支援的控制字元。','Text contains unsupported control characters.','文字包含不支持的控制字符。','未対応の制御文字が含まれています。','Text enthält nicht unterstützte Steuerzeichen.','Le texte contient des caractères de contrôle non pris en charge.','Текст содержит неподдерживаемые управляющие символы.'],
['題名與署名請使用單行。','Keep the title and byline on one line each.','题名与署名请使用单行。','題名と署名は各一行にしてください。','Titel und Verfasserangabe müssen jeweils einzeilig sein.','Le titre et la signature doivent chacun tenir sur une ligne.','Название и подпись должны быть однострочными.'],
['現金不能低於標價。','Cash tendered cannot be less than the price.','现金不能低于标价。','預かり金は価格以上にしてください。','Die Barzahlung darf nicht unter dem Preis liegen.','Les espèces remises ne peuvent être inférieures au prix.','Внесённая сумма не может быть ниже цены.'],
['不支援的字號。','Unsupported type size.','不支持的字号。','対応していない文字サイズです。','Nicht unterstützte Schriftgröße.','Corps non pris en charge.','Неподдерживаемый размер шрифта.'],
['排版時內容已改動，請再製作一次。','The text changed during typesetting. Please generate again.','排版时内容已改动，请重新制作。','組版中に内容が変更されました。もう一度作成してください。','Text während des Satzes geändert. Bitte erneut erstellen.','Le texte a changé pendant la composition. Recommencez.','Текст изменился во время вёрстки. Создайте заново.'],
['詩券已生成，可下載。沒有上傳文字，也沒有發出打印任務。','Your voucher is ready. No text was uploaded and no print job was sent.','诗券已生成，可下载。没有上传文字，也没有发出打印任务。','詩券ができました。文字の送信や印刷指示は行っていません。','Ihr Bon ist fertig. Kein Text wurde hochgeladen, kein Druckauftrag gesendet.','Votre bon est prêt. Aucun texte envoyé, aucune impression lancée.','Талон готов. Текст не отправлялся, задание печати не создавалось.'],
['作品目錄暫時無法載入，請重新整理。','The catalogue could not be loaded. Please reload.','作品目录暂时无法载入，请刷新。','作品一覧を読み込めません。再読み込みしてください。','Katalog konnte nicht geladen werden. Bitte neu laden.','Impossible de charger le catalogue. Actualisez la page.','Не удалось загрузить каталог. Обновите страницу.'],
['AUTHOR EDITION','AUTHOR EDITION','作者版本','作者版','AUTORENAUSGABE','ÉDITION DE L’AUTEUR','АВТОРСКАЯ ВЕРСИЯ'],
['READER EDITION','READER EDITION','访客版本','読者版','LESERAUSGABE','ÉDITION DU LECTEUR','ЧИТАТЕЛЬСКАЯ ВЕРСИЯ'],
['DIGITAL PROOF','DIGITAL PROOF','数字校样','デジタル校正','DIGITALE DRUCKVORSCHAU','ÉPREUVE NUMÉRIQUE','ЦИФРОВАЯ ПРОБА'],
['約','Approx.','约','約','Ca.','Env.','Около'],
['原站作品','Original publication','原站作品','原掲載ページ','Originalveröffentlichung','Publication originale','Оригинальная публикация']
];
// Longer project notes are kept separately for readable translation maintenance.
localeRows.push(
['小票以固定點陣字格排列交易、找零、機號與條碼。詩券預設使用各語言的點陣字體；網站字體版本則使用個人網站的 EB Garamond 與中日文字體。兩張紙以同一券號相連。','The receipt uses fixed bitmap cells for the transaction, change, terminal references and barcode. The voucher defaults to pixel typefaces for each supported language; the website-typeface edition uses the portfolio’s EB Garamond and Chinese/Japanese fonts. A shared reference joins the pieces.','小票以固定点阵字格排列交易、找零、机号与条码。诗券默认使用各语言的点阵字体；网站字体版本则使用个人网站的 EB Garamond 与中日文字体。两张纸以同一券号相连。','レシートは固定ドット文字で取引・お釣り・端末番号・バーコードを表示。詩券は各対応言語のドット書体が標準で、サイト書体版では個人サイトの EB Garamond と中国語・日本語書体を使います。同じ券番号で二つを結びます。','Der Bon setzt Transaktion, Wechselgeld, Gerätenummern und Barcode in feste Rasterzellen. Der Gedichtbon verwendet standardmäßig Pixelschriften für jede unterstützte Sprache; die Website-Schriftenausgabe nutzt EB Garamond sowie die chinesischen und japanischen Schriften des Portfolios. Eine Nummer verbindet beide Teile.','Le ticket utilise des cellules matricielles pour la transaction, la monnaie, les références et le code-barres. Le bon poétique utilise par défaut les polices matricielles de chaque langue prise en charge ; l’édition avec les polices du site emploie EB Garamond ainsi que les polices chinoises et japonaises du portfolio. Un numéro relie les deux parties.','В чеке используются фиксированные растровые ячейки для покупки, сдачи, номеров и штрихкода. Для поэтического талона по умолчанию используются пиксельные шрифты каждой поддерживаемой письменности; версия со шрифтами сайта использует EB Garamond и китайские и японские шрифты портфолио. Обе части связаны одним номером.'],
['收銀部分參照英國零售收據的資訊層級，並非任何超市的複製品。價格、現金與找零構成一筆虛構交易；票面明示 SPECIMEN，詩券無現金價值。','The receipt borrows the information hierarchy of British retail receipts, without copying a supermarket. Price, cash and change describe a fictional transaction. It is marked SPECIMEN; the voucher has no cash value.','收银部分参考英国零售收据的信息层级，并非任何超市的复制品。价格、现金与找零构成虚构交易；票面明示 SPECIMEN，诗券无现金价值。','英国の小売レシートの情報構造を参照していますが、特定のスーパーの複製ではありません。取引は架空です。SPECIMEN と明記され、金銭的価値はありません。','Die Informationshierarchie folgt britischen Kassenbons, ohne einen Supermarkt zu kopieren. Die Transaktion ist fiktiv, als SPECIMEN gekennzeichnet und ohne Geldwert.','La hiérarchie s’inspire des tickets britanniques sans reproduire une enseigne. La transaction est fictive, marquée SPECIMEN ; le bon n’a aucune valeur monétaire.','Структура основана на британских розничных чеках, без копирования конкретного магазина. Покупка вымышлена, чек помечен SPECIMEN; талон не имеет денежной стоимости.'],
['作品按 H10S 的 384 點打印寬度轉成 1-bit 黑白點陣。TILL 與 PRN 是獨立配置的公開機號，不含硬件序列號。此處展示數位校樣，實體紙面效果尚待標定。','The work becomes a 1-bit bitmap at the H10S’s 384-dot print width. TILL and PRN are assigned public aliases, not hardware serial numbers. These are digital proofs; the physical output still awaits calibration.','作品按 H10S 的 384 点打印宽度转换为 1-bit 黑白点阵。TILL 与 PRN 是独立配置的公开机号，不含硬件序列号。此处是数字校样，实体效果尚待标定。','H10S の印刷幅384ドットに合わせた1ビット白黒画像です。TILL と PRN は公開用の別名で、製造番号ではありません。実際の紙への出力は未校正です。','Das Werk wird als 1-Bit-Raster mit 384 Punkten Breite für den H10S gesetzt. TILL und PRN sind öffentliche Aliasnummern, keine Seriennummern. Der physische Druck ist noch nicht kalibriert.','L’œuvre est une image 1 bit de 384 points de large pour le H10S. TILL et PRN sont des alias publics, pas des numéros de série. L’impression physique reste à calibrer.','Работа преобразуется в чёрно-белый растр 1 бит шириной 384 точки для H10S. TILL и PRN — публичные псевдонимы, не серийные номера. Физическая печать ещё не откалибрована.'],
['選擇作者原作，或輸入自己的文字。排版和檔案生成都在瀏覽器中完成，不接入打印機。內置字體未收錄的字會由裝置字體補足，因此自訂文字的效果可能因裝置而異。','Choose an original work or enter your own text. Typesetting and file creation happen in your browser, without a printer connection. Characters missing from the bundled fonts fall back to device fonts, so custom text may look different across devices.','选择作者原作，或输入自己的文字。排版和文件生成都在浏览器中完成，不连接打印机。内置字体未收录的字会由设备字体补足，因此自定义文字的效果可能因设备而异。','原作を選ぶか自分の文字を入力できます。組版とファイル生成はブラウザー内で行い、印刷機には接続しません。内蔵フォントにない文字は端末のフォントで補われるため、表示は端末によって異なります。','Wählen Sie ein Original oder geben Sie eigenen Text ein. Satz und Dateierstellung bleiben im Browser, ohne Druckerverbindung. Zeichen, die in den mitgelieferten Schriften fehlen, werden durch Geräteschriften ergänzt; das Ergebnis kann je nach Gerät variieren.','Choisissez une œuvre ou votre propre texte. Composition et fichiers sont créés dans le navigateur, sans connexion à l’imprimante. Les caractères absents des polices intégrées utilisent celles de l’appareil ; le résultat peut varier.','Выберите оригинал или введите свой текст. Вёрстка и файлы создаются в браузере без подключения к принтеру. Символы, отсутствующие во встроенных шрифтах, берутся из шрифтов устройства, поэтому вид может различаться.']
);
// Original English headings also receive Chinese labels, rather than mixed UI.
const traditionalOverrides={'Make yours':'製作詩券','About':'關於作品','Portfolio':'作品集','Make an edition':'製作一個版本','From till':'從收銀','to text.':'到文字。','Back to portfolio':'返回作品集','AUTHOR EDITION':'作者版本','READER EDITION':'訪客版本','DIGITAL PROOF':'數位校樣','POETRY / INTERACTION / THERMAL PAPER · 2026':'詩歌 / 互動 / 熱敏紙 · 2026','MADE IN YOUR BROWSER · NO REMOTE PRINTING':'瀏覽器本地生成 · 不遠程打印','58 MM PAPER / 384 DOTS / 1 BIT':'58 毫米紙寬 / 384 點 / 1 bit','01 / SELECT & COMPOSE':'01 / 選擇與創作','02 / DIGITAL PROOF':'02 / 數位校樣','03 / PROJECT NOTES':'03 / 項目說明','POETRY VOUCHER · DIGITAL STUDY · 2026':'詩券 · 數位實驗 · 2026'};
const localeMap=new Map(localeRows.map(row=>[row[0],row]));
traditionalOverrides.Language='語言';
const portfolioLinks=[...document.querySelectorAll('a[href="https://hanpuli.github.io/"]')];
const portfolioWorkLinks=[...document.querySelectorAll('[data-portfolio-link]')];
function normaliseLocale(value){
  if(!value)return null;value=value.toLowerCase();
  if(['zh','zh-hant','zh-hant-hk','zh-tw','zh-hk'].includes(value))return 'zh-Hant';
  if(['zh-hans','zh-cn','zh-sg','zh-hans-cn'].includes(value))return 'zh-Hans';
  return ['en','ja','de','fr','ru'].find(lang=>value===lang||value.startsWith(lang+'-'))||null;
}
let uiLocale=normaliseLocale(new URL(location.href).searchParams.get('lang'))||normaliseLocale(document.documentElement.dataset.defaultLocale)||normaliseLocale(navigator.language)||'en';
const staticBindings=[];
const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
while(walker.nextNode()){
  const node=walker.currentNode,key=node.nodeValue.trim();
  if(node.parentElement?.closest('script,style,#ui-locale'))continue;
  if(localeMap.has(key))staticBindings.push({node,key,prefix:node.nodeValue.match(/^\s*/)[0],suffix:node.nodeValue.match(/\s*$/)[0]});
}
const attributeBindings=[];
document.querySelectorAll('[aria-label],[alt]').forEach(node=>{
  for(const attr of ['aria-label','alt']){const key=node.getAttribute(attr);if(localeMap.has(key))attributeBindings.push({node,attr,key});}
});
function tr(key){return uiLocale==='zh-Hant'&&traditionalOverrides[key]||localeMap.get(key)?.[localeNames.indexOf(uiLocale)]||key;}
function applyLocale(){
  const htmlLang={'en':'en-GB','zh-Hant':'zh-Hant-HK','zh-Hans':'zh-Hans','ja':'ja','de':'de','fr':'fr','ru':'ru'}[uiLocale];
  document.documentElement.lang=htmlLang;
  document.documentElement.dataset.uiLocale=uiLocale;
  document.getElementById('ui-locale').value=uiLocale;
  staticBindings.forEach(({node,key,prefix,suffix})=>node.nodeValue=prefix+tr(key)+suffix);
  attributeBindings.forEach(({node,attr,key})=>node.setAttribute(attr,tr(key)));
  document.title=tr('製作室')+' · Poetry Voucher · Hanpu Li';
  document.querySelector('meta[name="description"]').content=tr('製作詩券')+' · Hanpu Li · '+tr('MADE IN YOUR BROWSER · NO REMOTE PRINTING');
  const route={'en':'','zh-Hant':'zh/','zh-Hans':'zh-hans/','ja':'ja/','de':'de/','fr':'fr/','ru':'ru/'}[uiLocale];
  portfolioLinks.forEach(link=>link.href='https://hanpuli.github.io/'+route);
  portfolioWorkLinks.forEach(link=>link.href='https://hanpuli.github.io/'+route+'#work');
  document.querySelectorAll('[data-project-link]').forEach(link=>link.href='/'+route+'poetry-voucher/');
}
document.getElementById('ui-locale').addEventListener('change',event=>{
  uiLocale=event.target.value;applyLocale();
  const url=new URL(location.href);url.searchParams.set('lang',uiLocale);history.replaceState(null,'',url);
  document.dispatchEvent(new Event('presslocalechange'));
});
applyLocale();
