'use strict';
// Authored interface copy; literary text always comes from the published catalogue.
const SHOP_LANGS=['en','zh-Hant','zh-Hans','ja','de','fr','ru'];
const SHOP_COPY={
shop:['Shop','商店','商店','ショップ','Shop','Boutique','Магазин'],
bag:['Bag','購物袋','购物袋','買い物袋','Warenkorb','Panier','Корзина'],
deck:['A poem, by the piece.','詩，逐件出售。','诗，逐件出售。','詩を、一篇ずつ。','Gedichte, Stück für Stück.','Un poème, à la pièce.','Стихи, поштучно.'],
intro:['Browse the shelves. Choose an edition. Take a little language with you.','逛逛，選一個版本，帶走一點語言。','逛逛，选一个版本，带走一点语言。','棚を眺め、版を選び、言葉を少し持ち帰る。','Stöbern. Eine Ausgabe wählen. Ein wenig Sprache mitnehmen.','Parcourez les rayons. Choisissez une édition. Emportez un peu de langage.','Осмотритесь. Выберите издание. Унесите с собой немного языка.'],
browse:['Browse the collection ↓','瀏覽作品 ↓','浏览作品 ↓','作品を見る ↓','Sammlung ansehen ↓','Voir la collection ↓','Смотреть коллекцию ↓'],
editionNote:['Poems & lyrics · Original texts & paired editions','詩與詞 · 原文及對照版本','诗与词 · 原文及对照版本','詩と詞 · 原文と対訳版','Gedichte & Ci · Originale und zweisprachige Ausgaben','Poèmes & ci · Textes originaux et éditions bilingues','Стихи и цы · Оригиналы и параллельные издания'],
fiction:["Art editions", "藝術版本", "艺术版本", "アート作品", "Kunstausgaben", "Éditions d’art", "Художественные издания"],
collection:['On the shelves','架上作品','架上作品','棚の作品','Im Sortiment','En rayon','На полках'],
custom:['Bring your own words ↗','帶來自己的文字 ↗','带来自己的文字 ↗','自分の言葉を持ち込む ↗','Eigene Worte mitbringen ↗','Apporter vos mots ↗','Принести свои слова ↗'],
search:['Search poems','搜尋作品','搜索作品','作品を検索','Gedichte suchen','Rechercher un poème','Поиск стихов'],
filter:['Collection','作品集','作品集','作品集','Sammlung','Collection','Сборник'],
all:['All editions','全部作品','全部作品','すべての作品','Alle Ausgaben','Toutes les éditions','Все издания'],
cycle:['The A/B cycle','甲乙十六首','甲乙十六首','甲乙十六首','Der A/B-Zyklus','Le cycle A/B','Цикл A/B'],
lyrics:['Other lyrics','集外詞作','集外词作','その他の詞','Weitere Ci','Autres ci','Другие цы'],
roof:['The Roof Splits Open','屋頂裂開','屋顶裂开','屋根が裂ける','Das Dach reißt auf','Le toit se fend','Крыша раскалывается'],
noResults:['No editions found.','沒有符合的作品。','没有符合的作品。','該当する作品はありません。','Keine Ausgaben gefunden.','Aucune édition trouvée.','Издания не найдены.'],
colophonTitle:['Something to hold on to.','留住一點什麼。','留住一点什么。','手元に残るもの。','Etwas zum Festhalten.','Quelque chose à garder.','Что-то, что можно сохранить.'],
colophon:['A till counts characters, lines and pauses. The receipt records a transaction; the voucher keeps the poem. Nothing is charged. What you take away is an edition.','收銀機數着字、行與停頓。小票記錄交易，詩券留下作品。不扣款；帶走的是一個版本。','收银机数着字、行与停顿。小票记录交易，诗券留下作品。不扣款；带走的是一个版本。','レジは文字と行と間を数える。レシートは取引を記録し、券は詩を残す。料金はかからない。持ち帰るのは一つの版。','Die Kasse zählt Zeichen, Zeilen und Pausen. Der Beleg hält die Transaktion fest, der Bon das Gedicht. Es wird nichts berechnet. Was bleibt, ist eine Ausgabe.','La caisse compte caractères, lignes et pauses. Le reçu consigne la transaction ; le bon conserve le poème. Rien n’est débité. Vous emportez une édition.','Касса считает знаки, строки и паузы. Чек хранит сделку, талон — стихотворение. Деньги не списываются. Вы уносите издание.'],
about:['About this work ↗','關於這件作品 ↗','关于这件作品 ↗','この作品について ↗','Über dieses Werk ↗','À propos de cette œuvre ↗','Об этой работе ↗'],
configure:['Choose your edition','選擇版本','选择版本','版を選ぶ','Ausgabe wählen','Choisir votre édition','Выберите издание'],
close:['Close','關閉','关闭','閉じる','Schließen','Fermer','Закрыть'],
unitPrice:['Per edition','每份','每份','一部あたり','Pro Ausgabe','Par exemplaire','За экземпляр'],
add:['Add to bag','加入購物袋','加入购物袋','袋に入れる','In den Warenkorb','Ajouter au panier','В корзину'],
choose:['Read & choose','閲讀與選版','阅读与选版','読む・版を選ぶ','Lesen & wählen','Lire et choisir','Читать и выбрать'],
original:['Original · Pixel type · 24 dots','原文 · 點陣體 · 24 點','原文 · 点阵体 · 24 点','原文 · ドット書体 · 24点','Original · Pixelschrift · 24 Punkte','Original · Police pixel · 24 points','Оригинал · Пиксельный шрифт · 24 точки'],
paired:['Paired edition','對照版本','对照版本','対訳版','Parallelausgabe','Édition parallèle','Параллельное издание'],
draft:['Draft','草稿','草稿','草稿','Entwurf','Brouillon','Черновик'],
save:['Save changes','儲存更改','保存更改','変更を保存','Änderungen speichern','Enregistrer','Сохранить'],
saveCustom:['Save custom text on this device too','也在此裝置儲存自選正文','也在此设备保存自选正文','自作の本文もこの端末に保存','Eigene Texte auch auf diesem Gerät speichern','Enregistrer aussi les textes personnels sur cet appareil','Сохранять на устройстве и свой текст'],
privacy:['Custom text stays in this tab unless you choose to save it on this device.','自選正文只留在此分頁，除非你選擇在本機儲存。','自选正文只留在此标签页，除非你选择在本机保存。','自作の本文は、保存を選ぶまでこのタブだけに残ります。','Eigene Texte bleiben ohne ausdrückliche Speicherung nur in diesem Tab.','Les textes personnels restent dans cet onglet, sauf si vous choisissez de les enregistrer.','Свой текст остаётся только во вкладке, пока вы не выберете сохранение.'],
storage:['Catalogue selections are saved on this device. Custom text stays in this tab by default.','目錄選購會儲存在此裝置。自選正文預設只留在此分頁。','目录选购会保存在此设备。自选正文默认只留在此标签页。','選んだ既刊作品は端末に保存。自作の本文は通常このタブだけに残ります。','Katalogauswahl wird lokal gespeichert. Eigene Texte bleiben zunächst nur in diesem Tab.','Les choix du catalogue sont enregistrés ici. Les textes personnels restent par défaut dans cet onglet.','Выбор из каталога сохраняется на устройстве. Свой текст по умолчанию остаётся во вкладке.'],
storageError:['Device storage is unavailable. Your bag is kept in this tab only.','無法使用本機儲存。購物袋只留在此分頁。','无法使用本机存储。购物袋只留在此标签页。','端末に保存できません。このタブだけに保存されます。','Lokaler Speicher nicht verfügbar. Der Warenkorb bleibt nur in diesem Tab.','Stockage local indisponible. Le panier reste dans cet onglet.','Хранилище недоступно. Корзина остаётся только во вкладке.'],
total:['Total','總計','总计','合計','Gesamt','Total','Итого'],
noCharge:["No money will be taken.", "不會扣取任何款項。", "不会扣取任何款项。", "料金はかかりません。", "Es wird kein Geld abgebucht.", "Aucun montant ne sera débité.", "Деньги не списываются."],
checkout:['Go to checkout','前往結賬','前往结账','レジへ進む','Zur Kasse','Passer en caisse','К оформлению'],
continue:['Continue browsing','繼續逛逛','继续逛逛','買い物を続ける','Weiter stöbern','Continuer la visite','Продолжить просмотр'],
checkoutTitle:['Checkout','結賬','结账','お会計','Kasse','Caisse','Оформление'],
payment:['PAYMENT','付款','付款','お支払い','ZAHLUNG','PAIEMENT','ОПЛАТА'],
paymentText:["No payment is collected. No card details or personal information are needed.", "不收取款項，無需卡號或個人資料。", "不收取款项，无需卡号或个人资料。", "料金はかかりません。カード情報や個人情報は不要です。", "Keine Abbuchung. Keine Karten- oder persönlichen Daten nötig.", "Aucun débit. Aucune donnée bancaire ou personnelle requise.", "Деньги не списываются. Данные карты и личные сведения не нужны."],
delivery:['Your receipt and poetry vouchers will be prepared here, ready to download. No physical delivery.','小票與詩券將在此生成並供下載，不寄送實物。','小票与诗券将在此生成并供下载，不寄送实物。','レシートと詩の券をここで作成し、ダウンロードできます。配送はありません。','Beleg und Gedichtbons werden hier zum Download erstellt. Kein Versand.','Reçu et bons seront préparés ici pour téléchargement. Aucun envoi physique.','Чек и талоны будут созданы здесь для скачивания. Физической доставки нет.'],
place:["Complete purchase", "完成購買", "完成购买", "購入を確定", "Kauf abschließen", "Valider l’achat", "Завершить покупку"],
back:['Back to bag','返回購物袋','返回购物袋','袋に戻る','Zurück zum Warenkorb','Retour au panier','Назад в корзину'],
thankYou:['Thank you. These words are yours to keep.','謝謝惠顧。把這些字帶走吧。','谢谢惠顾。把这些字带走吧。','ありがとうございました。この言葉をお手元に。','Vielen Dank. Diese Worte bleiben bei Ihnen.','Merci. Ces mots sont à garder.','Спасибо. Сохраните эти слова.'],
empty:['Your bag is waiting for a poem.','購物袋正等着一首詩。','购物袋正等着一首诗。','袋は詩を待っています。','Ihr Warenkorb wartet auf ein Gedicht.','Votre panier attend un poème.','Ваша корзина ждёт стихотворения.'],
edit:['Edit','編輯','编辑','編集','Bearbeiten','Modifier','Изменить'],
remove:['Remove','移除','移除','削除','Entfernen','Retirer','Удалить'],
quantity:['Quantity','數量','数量','数量','Anzahl','Quantité','Количество'],
added:['Added to your bag.','已加入購物袋。','已加入购物袋。','袋に追加しました。','Zum Warenkorb hinzugefügt.','Ajouté au panier.','Добавлено в корзину.'],
updated:['Bag updated.','購物袋已更新。','购物袋已更新。','袋を更新しました。','Warenkorb aktualisiert.','Panier mis à jour.','Корзина обновлена.'],
limit:['Up to 24 vouchers per order.','每單最多 24 份詩券。','每单最多 24 份诗券。','一注文につき24部まで。','Bis zu 24 Bons pro Bestellung.','24 bons maximum par commande.','До 24 талонов в заказе.'],
preparing:['Preparing your editions…','正在整理你的詩券…','正在整理你的诗券…','作品を準備しています…','Ausgaben werden vorbereitet…','Préparation de vos éditions…','Готовим издания…'],
failed:['Could not prepare the order. Your bag is unchanged; please try again.','未能完成訂單。購物袋已保留，請重試。','未能完成订单。购物袋已保留，请重试。','作成できませんでした。袋はそのままです。再試行してください。','Bestellung konnte nicht erstellt werden. Ihr Warenkorb bleibt erhalten. Bitte erneut versuchen.','La préparation a échoué. Votre panier est conservé ; veuillez réessayer.','Не удалось подготовить заказ. Корзина сохранена. Повторите попытку.'],
loadError:['The collection could not be loaded. Please reload this page.','未能載入作品，請重新整理。','未能加载作品，请刷新。','作品を読み込めません。再読み込みしてください。','Sammlung konnte nicht geladen werden. Bitte neu laden.','Impossible de charger la collection. Rechargez la page.','Не удалось загрузить коллекцию. Обновите страницу.'],
receipt:['Receipt','小票','小票','レシート','Beleg','Reçu','Чек'],
orderPdf:['Download entire order · PDF','下載整單 · PDF','下载整单 · PDF','注文全体 · PDF','Gesamte Bestellung · PDF','Commande complète · PDF','Весь заказ · PDF'],
receiptPdf:['Download receipt · PDF','下載小票 · PDF','下载小票 · PDF','レシート · PDF','Beleg herunterladen · PDF','Télécharger le reçu · PDF','Скачать чек · PDF'],
order:['Order','訂單','订单','注文','Bestellung','Commande','Заказ'],
card:["Card", "刷卡", "刷卡", "カード", "Karte", "Carte", "Карта"],
cash:["Cash", "現金", "现金", "現金", "Bar", "Espèces", "Наличные"],
change:['Change','找零','找零','お釣り','Rückgeld','Monnaie rendue','Сдача'],
received:['Tendered','實收','实收','お預かり','Gegeben','Reçu','Внесено'],
required:['Please enter a title and a poem.','請填寫題名和正文。','请填写题名和正文。','題名と本文を入力してください。','Bitte Titel und Gedicht eingeben.','Saisissez un titre et un poème.','Введите название и стихотворение.'],
invalid:['Please check the text length and remove unsupported control characters.','請檢查文字長度及移除不支援的控制字元。','请检查文字长度及移除不支持的控制字符。','文字数と制御文字を確認してください。','Bitte Textlänge und Steuerzeichen prüfen.','Vérifiez la longueur du texte et les caractères de contrôle.','Проверьте длину текста и управляющие символы.'],
restored:['Your saved bag has been restored.','已還原儲存的購物袋。','已恢复保存的购物袋。','保存された袋を復元しました。','Gespeicherter Warenkorb wiederhergestellt.','Votre panier a été restauré.','Сохранённая корзина восстановлена.'],
recovered:['Some saved selections could not be restored. Please check your bag.','部分已存選購未能還原，請核對購物袋。','部分已存选购未能恢复，请核对购物袋。','一部の選択を復元できませんでした。袋を確認してください。','Einige Auswahlen konnten nicht wiederhergestellt werden. Bitte Warenkorb prüfen.','Certains choix n’ont pas pu être restaurés. Vérifiez le panier.','Часть выбора не восстановлена. Проверьте корзину.'],
downloadHint:['Downloads remain available in this tab. Save them before leaving.','下載會保留在此分頁，離開前請保存。','下载会保留在此标签页，离开前请保存。','ダウンロードはこのタブに残ります。閉じる前に保存してください。','Downloads bleiben in diesem Tab. Vor dem Verlassen speichern.','Les téléchargements restent dans cet onglet. Enregistrez-les avant de partir.','Скачивания доступны в этой вкладке. Сохраните их перед выходом.'],
stageCollection:['01 / COLLECTION','01 / 作品','01 / 作品','01 / 作品集','01 / SAMMLUNG','01 / COLLECTION','01 / КОЛЛЕКЦИЯ'],
stageBag:['02 / YOUR SELECTION','02 / 你的選購','02 / 你的选购','02 / 選んだ作品','02 / IHRE AUSWAHL','02 / VOTRE SÉLECTION','02 / ВАШ ВЫБОР'],
stageCheckout:['03 / AT THE TILL','03 / 收銀台','03 / 收银台','03 / レジにて','03 / AN DER KASSE','03 / À LA CAISSE','03 / У КАССЫ'],
stageOrder:['04 / YOUR EDITIONS','04 / 你的詩券','04 / 你的诗券','04 / あなたの詩の券','04 / IHRE AUSGABEN','04 / VOS ÉDITIONS','04 / ВАШИ ИЗДАНИЯ'],
readFull:['Read the complete poem','閲讀全詩','阅读全文','詩の全文を読む','Das ganze Gedicht lesen','Lire le poème entier','Читать стихотворение целиком'],
readingNote:['Reading in your interface language. Choose the printed language in Edition below.','以下按介面語言閲讀；詩券語言請在下方「版本」選擇。','以下按界面语言阅读；诗券语言请在下方“版本”选择。','表示言語での閲覧です。券の言語は下の「版」で選択してください。','Lesefassung in Ihrer Sprache. Die Sprache des Bons wählen Sie unten unter Ausgabe.','Lecture dans la langue de l’interface. Choisissez la langue du bon sous Édition ci-dessous.','Чтение на языке интерфейса. Язык талона выберите ниже в разделе «Версия».'],
originalLanguage:['Original text · Traditional Chinese','原文 · 繁體中文','原文 · 繁体中文','原文 · 繁体字中国語','Originaltext · Traditionelles Chinesisch','Texte original · Chinois traditionnel','Оригинал · Традиционный китайский'],
receiptArtwork:['The thermal receipt uses English till lettering. Your order details and controls are shown in your chosen language.','熱敏小票沿用英文收銀字樣；訂單明細與操作按你的語言顯示。','热敏小票沿用英文收银字样；订单明细按你选择的语言显示。','感熱レシートは英語のレジ表記です。注文内容と操作は選択した言語で表示されます。','Der Thermobeleg verwendet englische Kassenbeschriftungen. Bestelldetails und Bedienung erscheinen in Ihrer Sprache.','Le reçu thermique conserve ses libellés de caisse en anglais. Les détails et commandes sont affichés dans votre langue.','Термочек использует английские кассовые надписи. Детали заказа и управление показаны на выбранном языке.'],
};
